### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by alexzhc** [piraeusdatastore/milestones#1]
## Containerization
- [ ] postgres cluster （before etcd support is ready)
- [ ] linstor controller
- [ ] linstor satellite 

## Ochestration
- [ ] Yaml-based deployment
- [ ] Operator-based deployment
- [ ] CSI support for Kube 1.10 

## Automation
- [ ] self-discovered node registration
- [ ] explicit separation of data and management network
- [ ] in-place compilation and loading of drbd module
- [ ] Drop drbd-util and linstor-client from container to OS

## Linstor
- [ ] experimental file-backend as the out-of-box DemoPool

## Documentation
- [ ] basic documenation rendered by hugo
